# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_notice = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_notice.setGeometry(QtCore.QRect(10, 10, 401, 71))
        self.textEdit_notice.setObjectName("textEdit_notice")
        self.pushButton_return = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_return.setGeometry(QtCore.QRect(410, 10, 61, 71))
        self.pushButton_return.setObjectName("pushButton_return")
        self.textEdit_usb_1 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_usb_1.setGeometry(QtCore.QRect(110, 90, 356, 50))
        self.textEdit_usb_1.setObjectName("textEdit_usb_1")
        self.textEdit_usb_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_usb_2.setGeometry(QtCore.QRect(110, 150, 356, 50))
        self.textEdit_usb_2.setObjectName("textEdit_usb_2")
        self.textEdit_usb_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_usb_3.setGeometry(QtCore.QRect(110, 210, 356, 50))
        self.textEdit_usb_3.setObjectName("textEdit_usb_3")
        self.label_usb_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_usb_1.setGeometry(QtCore.QRect(10, 90, 101, 51))
        self.label_usb_1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_usb_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_usb_1.setObjectName("label_usb_1")
        self.progressBar_usb_1 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_usb_1.setGeometry(QtCore.QRect(10, 120, 100, 20))
        self.progressBar_usb_1.setStyleSheet("")
        self.progressBar_usb_1.setProperty("value", 0)
        self.progressBar_usb_1.setObjectName("progressBar_usb_1")
        self.label_usb_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_usb_2.setGeometry(QtCore.QRect(10, 150, 101, 51))
        self.label_usb_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_usb_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_usb_2.setObjectName("label_usb_2")
        self.label_usb_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_usb_3.setGeometry(QtCore.QRect(10, 210, 101, 51))
        self.label_usb_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_usb_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_usb_3.setObjectName("label_usb_3")
        self.progressBar_usb_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_usb_3.setGeometry(QtCore.QRect(10, 240, 100, 20))
        self.progressBar_usb_3.setStyleSheet("")
        self.progressBar_usb_3.setProperty("value", 0)
        self.progressBar_usb_3.setObjectName("progressBar_usb_3")
        self.progressBar_usb_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_usb_2.setGeometry(QtCore.QRect(10, 180, 100, 20))
        self.progressBar_usb_2.setStyleSheet("")
        self.progressBar_usb_2.setProperty("value", 0)
        self.progressBar_usb_2.setObjectName("progressBar_usb_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_return.setText(_translate("MainWindow", "返回"))
        self.label_usb_1.setText(_translate("MainWindow", "usb1"))
        self.label_usb_2.setText(_translate("MainWindow", "usb2"))
        self.label_usb_3.setText(_translate("MainWindow", "usb3"))
